/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame_Plot.java
 *
 * Created on 12 Apr, 2009, 10:34:18 PM
 */
package nanoplot;

import java.io.File;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Amit
 */
public class JFrame_Plot extends javax.swing.JFrame {

    List xyDataGiven = new Vector();
    JPanel_Plot plot = new JPanel_Plot();
    //JDialog_Plot_Settings plotSettings = new JDialog_Plot_Settings(plot);

    /** Creates new form JFrame_Plot */
    public JFrame_Plot() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrame_Plot.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            Logger.getLogger(JFrame_Plot.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            Logger.getLogger(JFrame_Plot.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrame_Plot.class.getName()).log(Level.SEVERE, null, ex);
        }


        initComponents();


        //xyData.clear();

//        for (int i = 0; i < 4; i++) {
//            float[] xxx = new float[2];
//            xxx[0] = i + 1;
//            xxx[1] = i * 10;
//            xyDataGiven.add(i, xxx);
//        }


        plot.setDefaultValues();
        //plot.dynamicPlot(xyDataGiven);

        jPanel1.add(plot);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_File_Open = new javax.swing.JMenuItem();
        jMenuItem_File_Close = new javax.swing.JMenuItem();
        jMenuItem_File_Exit = new javax.swing.JMenuItem();
        jMenu_Edit = new javax.swing.JMenu();
        jMenuItem_Edit_Settings = new javax.swing.JMenuItem();
        jMenu_Help = new javax.swing.JMenu();
        jMenuItem_Help_QuickStart = new javax.swing.JMenuItem();
        jMenuItem_Help_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setLayout(new java.awt.GridLayout());

        jMenu_File.setText("File");

        jMenuItem_File_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_File_Open.setText("Open");
        jMenuItem_File_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_File_OpenActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_File_Open);

        jMenuItem_File_Close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_File_Close.setText("Close");
        jMenuItem_File_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_File_CloseActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_File_Close);

        jMenuItem_File_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_File_Exit.setText("Exit");
        jMenuItem_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_File_ExitActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_File_Exit);

        jMenuBar1.add(jMenu_File);

        jMenu_Edit.setText("Edit");

        jMenuItem_Edit_Settings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Edit_Settings.setText("Settings");
        jMenuItem_Edit_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Edit_SettingsActionPerformed(evt);
            }
        });
        jMenu_Edit.add(jMenuItem_Edit_Settings);

        jMenuBar1.add(jMenu_Edit);

        jMenu_Help.setText("Help");

        jMenuItem_Help_QuickStart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem_Help_QuickStart.setText("Quick Start");
        jMenuItem_Help_QuickStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Help_QuickStartActionPerformed(evt);
            }
        });
        jMenu_Help.add(jMenuItem_Help_QuickStart);

        jMenuItem_Help_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Help_About.setText("About");
        jMenuItem_Help_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Help_AboutActionPerformed(evt);
            }
        });
        jMenu_Help.add(jMenuItem_Help_About);

        jMenuBar1.add(jMenu_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_File_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_File_OpenActionPerformed
        jPanel1.setVisible(true);

        JFileChooser fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //log.append("Opening: " + file.getName() + "." + newline);
            String fileName = file.getAbsolutePath();

            FloatDataFileReader reader = new FloatDataFileReader(fileName);
            xyDataGiven = reader.getData();
            plot.dynamicPlot(xyDataGiven);
            plot.setVisible(true);
        }
        else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_jMenuItem_File_OpenActionPerformed

    private void jMenuItem_File_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_File_CloseActionPerformed
        plot.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jMenuItem_File_CloseActionPerformed

    private void jMenuItem_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_File_ExitActionPerformed
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_File_ExitActionPerformed

    private void jMenuItem_Edit_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Edit_SettingsActionPerformed
        plot.setSettingsVisible(true);
    }//GEN-LAST:event_jMenuItem_Edit_SettingsActionPerformed

    private void jMenuItem_Help_QuickStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Help_QuickStartActionPerformed
        JDialog_QuickStart qs = new JDialog_QuickStart(this, true);
        qs.setLocationRelativeTo(this);
        qs.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Help_QuickStartActionPerformed

    private void jMenuItem_Help_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Help_AboutActionPerformed
        JDialog_About aboutBox = new JDialog_About(this, true);
        aboutBox.setLocationRelativeTo(this);
        aboutBox.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Help_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrame_Plot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Edit_Settings;
    private javax.swing.JMenuItem jMenuItem_File_Close;
    private javax.swing.JMenuItem jMenuItem_File_Exit;
    private javax.swing.JMenuItem jMenuItem_File_Open;
    private javax.swing.JMenuItem jMenuItem_Help_About;
    private javax.swing.JMenuItem jMenuItem_Help_QuickStart;
    private javax.swing.JMenu jMenu_Edit;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Help;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
